version: '3'
services:
  master:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    image: divy4/jenkins-docker-swarm-master:latest
    networks:
    - jenkins-net
    ports:
    - "80:8080"
    - "50000:50000"
    volumes:
    - jenkins-log:/var/log/jenkins
    - jenkins-data:/var/jenkins_home
  slave:
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    image: divy4/jenkins-docker-swarm-slave:latest
    networks:
    - jenkins-net
volumes:
  jenkins-data:
  jenkins-log:
networks:
  jenkins-net:
